name: tf-plan

on:
  workflow_call:
    secrets:
      aws_role_to_assume:
        required: true
    inputs:
      env:
        required: true
        type: string

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
          
      - name: tf-plan-${{inputs.env}}
        run: |
          BUCKET_NAME="${{inputs.env}}-test-bucket-${{ github.run_id }}"
          echo "Creating bucket: $BUCKET_NAME"
          aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1