name: tf-plan

on:
  push:
    branches: [main]
  
permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
          
      - name: AWS WhoAmI and S3 upload
        run: |
          echo "files in current directory:"
          ls .
          aws sts get-caller-identity

          BUCKET_NAME="test-bucket-${{ github.run_id }}"
          echo "Creating bucket: $BUCKET_NAME"
          aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1
          
      - name: Decode GitHub OIDC token
        run: |
          echo "Requesting OIDC token..."
          TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "::add-mask::$TOKEN"
          echo "$TOKEN" | jq -r '.value' | cut -d "." -f2 | base64 -d | jq